algoritmo "Escolha_Caso_3"
var
   num: inteiro
inicio
      Escreval ("[1] para dizer 'Ola'")
      EscrevaL ("[2] para dizer 'Que doidera mano'")
      EscrevaL ("[3] para sair do programa")
      Leia (num)
      Escolha num
              Caso 1
              EscrevaL ("Ola")
              Caso 2
              Escreval ("Que doidera mano")
              Caso 3
              Escreval ("obrigado volte sempre")
              fimalgoritmo
      FimEscolha
fimalgoritmo