algoritmo "Estrelinha_Procedimento"
var
   Numero: inteiro
Procedimento Desenho (NDesenho: Inteiro)

Var
Contador: Inteiro

Inicio
      Para Contador <- 1 ate NDesenho passo 1 faca
              Para Contador <- 1 ate NDesenho passo 1 faca
              Escreva ("* ")
              FimPara
              EscrevaL
      FimPara
FimProcedimento

inicio
      Escreva ("Digite um numero: ")
      Leia (Numero)
      LimpaTela
      Desenho (Numero)
fimalgoritmo